exp_path: "/home/rdaneel/exp_aaai/"
ins_num: 25
time_limit: 60
plot_ci: true

f_weights:
  - 1.01
  - 1.02
  - 1.05
  - 1.10

maps:
  - name: Berlin_1_256
    label: city
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

  - name: den520d
    label: den520d
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

  - name: brc202d
    label: brc202d
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

  - name: warehouse-20-40-10-2-1
    label: warehouse
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

  - name: maze-32-32-2
    label: maze
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50

  - name: room-32-32-4
    label: room
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50

  - name: random-32-32-20
    label: random
    scens:
      - even
      - random
    num_of_agents:
      - 20
      - 40
      - 60
      - 80
      - 100

  - name: empty-32-32
    label: empty
    scens:
      - even
      - random
    num_of_agents:
      - 100
      - 200
      - 300
      - 400
      - 500

solvers:
  - name: EECBS0
    label: 'EECBS+'
    color: 'grey'
    marker: 'P'
    w: 1.02
    mtth: -1
    T_N: -1
    T_i: -1

  - name: EECBS3
    label: 'EECBS+ (FA*:30)'
    color: 'green'
    marker: 's'
    w: 1.02
    mtth: -1
    T_N: -1
    T_i: 30  

  - name: FEECBS0
    label: 'FEECBS+'
    color: 'deepskyblue'
    marker: 'o'
    w: 1.02
    mtth: -1
    T_N: -1
    T_i: -1
  
  - name: FEECBS3
    label: 'FEECBS+ (FR:50)'
    color: 'purple'
    marker: '>'
    w: 1.02
    mtth: -1
    T_N: 50
    T_i: -1

  - name: FEECBS8
    label: 'FEECBS+ (FA*:30)'
    color: 'gold'
    marker: '*'
    w: 1.02
    mtth: -1
    T_N: 50
    T_i: -1
  
  - name: FEECBS13
    label: 'FEECBS+ (FR:50,FA*:40)'
    color: 'red'
    marker: '^'
    w: 1.02
    mtth: -1
    T_N: 50
    T_i: 40
